### ISSUE TITLE
FindMedia failing

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#227]
On windows, if the path used to libraries are UNC path, and not mapped drives

**Comment by ukdtom** [comment]
@creoludifico 

Are you seen this error, cuz I do fail on reproducing here :-(

**Comment by creoludifico** [comment]
@ukdtom 
I'll send you some logs over skype soon
![image](https://cloud.githubusercontent.com/assets/12425208/22178403/5f3f9bfe-e035-11e6-83f6-6aea1aebdb44.png)

**Comment by creoludifico** [comment]
I've merged my branch with your latest work which fixed the problem
Good job tommy! 
d814ab967b3f0b9d5e20a5f4f68b1784b50fab2f

**Comment by ukdtom** [comment]
And as such, I conclude that you also can't reproduce here....DARN...

**Comment by creoludifico** [comment]
So that wasnt the problem?

**Comment by ukdtom** [comment]
Might still be an issue for the user, so we have to get him to test ;-)

**Comment by creoludifico** [comment]
Oh okay

**Comment by NIronwolf** [comment]
I received your test version but I am unable to get past the first login page with it.  I can confirm it did say 2.4 DEV on the header though.

Also restored my previous version (2..3) to make sure something else hadn't gone sideways and it logged right in. 

I've send a log link to you on the forums.

**Comment by creoludifico** [comment]
Hi @NIronwolf 

Have you checked out the branch oliver-work?
If not please try that and give it one more go.

Oliver

**Comment by ukdtom** [comment]
I sadly think the reason is something else here ;-)

I still need to fix https://github.com/ukdtom/WebTools.bundle/issues/232

@NIronwolf Open up the file named VERSION in the root of the WebTools.bundle dir with notepad, and delete everythin in it. then type the word test, and without pressing enter.

Save that, and restart PMS.

Can you then authenticate?

**Comment by NIronwolf** [comment]
![image](https://cloud.githubusercontent.com/assets/635345/22182145/04407e96-e05b-11e6-8040-9d1fb59c76ce.png)

An update window comes up and prevents me from moving on to the rest of the app.  :grinning:

**Comment by ukdtom** [comment]
This is good news, cuz I needed this tested ;-)

Try and redownload this one: https://github.com/ukdtom/WebTools.bundle/archive/tommy-work.zip

Then report back please

**Comment by NIronwolf** [comment]
Ok that version loaded up.

![image](https://cloud.githubusercontent.com/assets/635345/22182365/f288c766-e060-11e6-8989-332ea56a3701.png)

It is giving different results at least.

I think there are some titles missing.  I have 2093 directories (that should all have one movie each in them) but only 2071 titles are coming up.  I did look through and found 3 that had 'versions' that I need to clean up, but that doesn't cover the difference.  Do you need me to try to reconcile manually?

The Missing From Filesystem section seems to be the whole list (unverified).

I'll PM a new log set.

**Comment by ukdtom** [comment]
Fixed in https://github.com/ukdtom/WebTools.bundle/commit/25fd4e3fb0597a701ce723f4333b502f86e8eca4

@NIronwolf Care to redownload once more?
Seems like I finally could reproduce this ;-)

**Comment by ptr727** [comment]
Hi, same problem fore me, result with the above fix still shows many if not all files as missing, but they are there:

```
Missing From Filesystem
\\STORAGE\Media\Movies\Movies\The 'Burbs (1989)\The 'Burbs (1989).mkv
\\STORAGE\Media\Movies\Movies\1 Life on the limit (2013)\1 Life on the limit (2013).mkv
\\STORAGE\Media\Movies\Movies\10 (1979)\10 (1979).mkv
\\STORAGE\Media\Movies\Movies\The 11th Hour (2007)\The 11th Hour (2007).avi
\\STORAGE\Media\Movies\Movies\12 Years a Slave (2013)\12 Years a Slave (2013).mkv
...
```

**Comment by ukdtom** [comment]
In the root of the WebTools.bundle dir, could you create an empty file named "debug", and case sensitive

Then, if not wanting to restart PMS, rename WebTools.bundle dir to WebTools.bundle.tmp, wait until it's disappeared from channels view, and then rename back (Hack to just restart WT)

Then reproduce, and after that, grap ALL wt log files in a zip, and provide me with a link to them

**Comment by ptr727** [comment]
Ok, log directory here: https://1drv.ms/u/s!AqeqhT0NczrNhPRGS6BBbGMfmETb0w
Btw, same problem with TV show files, Movie and TV shows tested and in log.

**Comment by ukdtom** [comment]
Hmmm......the debug file was not picked up!
(Causing log entries to be missed here)
Please verify, that the file is named debug, and with NO extension at all!

**Comment by ptr727** [comment]
Main UI says: "Webtools - v2.4 DEV ****** WARNING Debug mode on *********"
I included the entire logs directory.

**Comment by ukdtom** [comment]
@ptr727 
Very odd, cus missing a lot of log info here.

Was this from the tommy-work thread only, and was everything replaced?

**Comment by ptr727** [comment]
Yes, save as zip, and replace the folder.
As FYI the original find missing and find unmatched plugins worked fine using UNC paths on Windows, they just no longer work with the DB schema changes, maybe look there to see how to handle the paths.

**Comment by ukdtom** [comment]
Well....Since I did write those, I kinda thought I did copy lots of the code over, but guess I missed something here.....SIGH...

**Comment by ptr727** [comment]
Or, maybe Plex changed something that broke the old code?
Anyway, let me know if I can test or try other things tonight when I get home.

**Comment by ukdtom** [comment]
@ptr727 

Could you please redownload the tommy-work branch, add the debug file, and then reupload a new set of logs, since I added a bit more logging here, in order to track this. Sadly simply can't reproduce :-(

**Comment by ukdtom** [comment]
Ans same goes for you @NIronwolf

**Comment by ptr727** [comment]
Here you go: https://1drv.ms/u/s!AqeqhT0NczrNhPZMuA5AAi3YgUWWlg

**Comment by ukdtom** [comment]
Thanks, but sadly, it wasn't enough logging I enabled here :-(

It simply will not scan you filesystem, only the database....

I need to enhance logging to the extreme I guess :-(

I'll return when done

**Comment by ukdtom** [comment]
And done, so @ptr727 please repeat the procedure ;-)

And when said, bed time here, so will have to wait until tomorrow to look into this

**Comment by ptr727** [comment]
Logs: https://1drv.ms/u/s!AqeqhT0NczrNhPhPLjFfvNsFQcyBSA

**Comment by ukdtom** [comment]
@ptr727 Sorry, but ready for a new stab at it?

**Comment by ptr727** [comment]
At the office, will test when I get home.

**Comment by ptr727** [comment]
Logs: https://1drv.ms/u/s!AqeqhT0NczrNhPsugGpbpskI34lmxg

**Comment by ukdtom** [comment]
Check forum PM

**Comment by ukdtom** [comment]
Fix verified by @ptr727

**Comment by NIronwolf** [comment]
I'd like to report that I'm home again from work travel and it appears to be working correctly.  It found several .VOB based copies that Plex had indeed not loaded.

Great work!  Let me know if you want a log set.
