### ISSUE TITLE
New line in VERSION on git pull

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#232]
When pulling via git the following issue occur.
The VERSION file gets a newline which makes it impossible to login because of HTTP 500 error.

**Comment by ukdtom** [comment]
I simply can't replicate on Linux here....
Could you attach a faulty version file please

**Comment by creoludifico** [comment]
[VERSION.txt](https://github.com/ukdtom/WebTools.bundle/files/721208/VERSION.txt)

**Comment by ukdtom** [comment]
Fixed ?

https://github.com/ukdtom/WebTools.bundle/commit/aea705b111ebc1604cb2ed9d496f81a5210e4e56

**Comment by creoludifico** [comment]
I still gets the error with the "\n".
I guess it's both the newline and the "\n" newline that is causing the error.
Try keeping the "\n" replace. 
[VERSION.txt](https://github.com/ukdtom/WebTools.bundle/files/721384/VERSION.txt)

**Comment by ukdtom** [comment]
Darn, cuz doesn't show on Linux here :-1: 

Guess I have to migrate to the dark side for a short time then for testing, but have no fear...I will return ;-)

**Comment by ukdtom** [comment]
Fixed with https://github.com/ukdtom/WebTools.bundle/commit/d5e55c26c81305b1f4bbd2e4d456e067d08a042b

**Comment by creoludifico** [comment]
Beautiful. 
Confirmed working
