### ISSUE TITLE
Logs: Triggers color change incorrectly

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#289]
See forum thread:
https://forums.plex.tv/discussion/comment/1411538/#Comment_1411538

**Comment by creoludifico** [comment]
Should have been fixed with V3

**Comment by ukdtom** [comment]
Not fixed.
Created an entry like:
`2017-04-13 12:57:03,240 (7f32ce321700) : INFO (webSrv:127) - Tester om ERROR CRITICAL EXCEPTION fanges af log viewer`

It needs to trigger on like `:ERROR`
Note the colon in front

**Comment by creoludifico** [comment]
![image](https://cloud.githubusercontent.com/assets/12425208/25563334/a2266efe-2d9a-11e7-9188-d2b3e96750c4.png)

**Comment by creoludifico** [comment]
What's wrong?

**Comment by ukdtom** [comment]
You are triggering on the msg itself.
You should trigger on what's in front of the actual msg.

Like if you have a line like:
`2017-04-30 11:57:23,071 (7fa9a8496700) : CRITICAL (runtime:709) - Private handlers are no longer supported; couldn't register >`

Trigger part is:
`2017-04-30 11:57:23,071 (7fa9a8496700) : CRITICAL (runtime:709)`

msg part is:
`Private handlers are no longer supported; couldn't register >`

With above, it'll not flag a scanner log for a movie named "Errors on MovieLand", if an info line for that is in the log

/T

**Comment by creoludifico** [comment]
There are so many different patterns on these log files. I've spliced the string on " - "
So i'll only look at the part before the space, the hyphen and the space. If the log file change in the future this wont work. Lets hope ;)

**Comment by ukdtom** [comment]
Absolutely valid workaround, IMHO
